osx_image: xcode7.3
language: objective-c

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install xcpretty
script:
  - pod lib lint --use-libraries
  - make install
  - make test

notifications:
 email: false
